### ISSUE TITLE
add option to specify base branch of release PR

### ISSUE THREAD

**Issue by jbibla** [faboweb/simsala#17]
when release PRs are open in our new flow - we have to manually change the base branch from develop to master. would be nice to choose a default!

**Comment by faboweb** [comment]
Can elaborate more? What new flow? Why would you want to target the release against master?

**Comment by jbibla** [comment]
new flow = we used to merge release branches to master, but now we release them to develop

well, for one, as separate tool it seems like this flexibility would be useful to others. 

i am hoping that our new new release flow for lunie will involve a human being merging something to master to trigger release deployments. would make sense to me if the release PRs that simsala makes for us were pointed at master in this case.

**Comment by faboweb** [comment]
>  would make sense to me if the release PRs that simsala makes for us were pointed at master in this case.
I disagree. then you would still need to merge master back to develop to remove the old changes, which we had before and caused also conflicts.

**Comment by faboweb** [comment]
You can already change the target branch though:

```
npx simsala release-candidate --help
```

```
Usage: release-candidate [options]

Options:
  -s, --semver <semver type>             Which version (patch|minor|mayor|prerelease) your want to increase? (default: "patch")    
  -p, --pending-path <pending path>      Where are pending files located? (default: "./pending")
  -c, --changelog-path <changelog path>  Where is the changelog located? (default: "./CHANGELOG.md")
  -o, --owner <owner>                    Name of the owner or organization of the repository. (guessed from origin if empty)       
  -r, --repository <repository>          Name of the repo. (guessed from origin if empty)
  -t, --token <github auth token>        Token to authenticate to GitHub (to push chages).
  -m, --message <message>                Message to prepend to the changes in the release PR description.
  -b, --target-branch <branch>           Branch the release PR is merged into. (default: "develop")
  -x, --tag-prefix <prefix>              Prefix version tags
  -h, --help                             output usage information
```

**Comment by jbibla** [comment]
> You can already change the target branch though:

awesome. the readme is out of date 😉 

> merge master back to develop to remove the old changes

this is a simsala issue though, no?

**Comment by faboweb** [comment]
> merge master back to develop to remove the old changes

no, that is a git issue. u have to persist, that changes got included in the changelog. Simsala does this but git needs to persist it. Lunie uses the CHANGELOG.md to release which causes conflicts on hotfixes explained in the according issue in Lunie.

**Comment by jbibla** [comment]
i don't understand what you're talking about but `-b, --target-branch` already exists which is great
